# Path for oh-my-zsh installation.
export ZSH=/home/diego/.oh-my-zsh

# Set name of the theme to load
ZSH_THEME="ys"

# Which plugins would you like to load?
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration
export LANG=en_US.UTF-8

